.circleci/config.yml, package.json, server/__tests__/index.test.js, server/package.json, yarn.lock
- Added circle ci config file.
- Added Default tests for server.
Fixes #2 
=> feat: Integrate Circle CI.

server/.babelrc, server/jest.config.js, server/package.json, server/src/app.js, server/src/env.js, server/src/index.js, server/src/thirdparty/README.md, server/src/thirdparty/__tests__/index.test.js, server/src/thirdparty/__tests__/routes/slack.test.js, server/src/thirdparty/__tests__/services/slack.test.js, server/src/thirdparty/__tests__/util/inMemoryDb.js, server/src/thirdparty/event.js, server/src/thirdparty/index.js, server/src/thirdparty/models/ThirdPartyApp.js, server/src/thirdparty/routes/index.js, server/src/thirdparty/routes/slackRouter.js, server/src/thirdparty/slackAPI/README.md, server/src/thirdparty/slackAPI/config.js, server/src/thirdparty/slackAPI/controller.js, server/src/thirdparty/slackAPI/service.js, server/src/thirdparty/utils/restUtil.js
- Create an design for thirdparty integration
- DB design for storing integrated app data
- Create event listeners for new app added, new event
- API to generate event 
- Test utils to use MongoMemoryServer
Fixes #23 
Created test files to test the basic endpoints  and used MongoMemoryServer to test DB apis.
=> feat:Create framework for thirdparty intgration

server/package.json, server/src/app.js, server/src/app/__tests__/index.test.js, server/src/app/__tests__/userLogin.test.js, server/src/app/__tests__/userRegister.test.js, server/src/app/constants/generateJwt.js, server/src/app/constants/packageConfig.js, server/src/app/controllers/userLogin.js, server/src/app/controllers/userLogout.js, server/src/app/controllers/userRegister.js, server/src/app/middlewares/auth.js, server/src/app/models/User.js, server/src/app/routes/index.js, server/src/app/routes/users.js, server/src/env.js, server/src/envVariable.js, server/src/index.js, server/src/thirdparty/slackAPI/service.js, yarn.lock
Fixes #14 #15 #16 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Setup JWT Authentication

.gitignore, Procfile, server/package.json
- Deployed backend server in Heroku
- Added it in pipeline, so every PR will deploy a server in Heroku and post it in GIT
Fixes #31 
Chore - deployment
=> chore: Deploy server in heroku

package.json, server/package.json, server/src/app.js, server/src/app/README.md, server/src/app/__tests__/routes/flux.test.js, server/src/app/__tests__/userRegister.test.js, server/src/app/controllers/fluxController.js, server/src/app/controllers/integratedAppController.js, server/src/app/controllers/userLogin.js, server/src/app/controllers/userRegister.js, server/src/app/middlewares/auth.js, server/src/app/models/Flux.js, server/src/app/models/IntegratedApps.js, server/src/app/routes/fluxRouter.js, server/src/app/routes/index.js, server/src/app/routes/integRouter.js, server/src/app/routes/integratedAppRouter.js, server/src/app/service/fluxService.js, server/src/app/service/integratedAppService.js, server/src/app/service/integrationService.js, server/src/index.js, server/src/logger/index.js, server/src/thirdparty/__tests__/util/inMemoryDb.js, server/src/thirdparty/config.js, server/src/thirdparty/routes/index.js, server/src/thirdparty/slackAPI/service.js, yarn.lock
- Add models for flux and integratedApps.
- Add CRUD endpoints for flux.
- Add workflow for flux execution.
- Take authtoken from both cookie and header.
Fixes #33 #29 #38
=> feat: Complete Flux workflow

server/src/app.js, server/src/app/__tests__/userRegister.test.js, server/src/app/controllers/userLogin.js, server/src/app/controllers/userRegister.js, server/src/app/middlewares/auth.js, server/src/app/routes/users.js
=> Fix: Fix cors issue, Add common response for all APIs.

client/package.json, client/src/Component/CreateFlux/CreateFlux.js, client/src/Component/CreateFlux/CreateFluxBody/ActionSection/Action.module.scss, client/src/Component/CreateFlux/CreateFluxBody/ActionSection/ActionSection.js, client/src/Component/CreateFlux/CreateFluxBody/CreateFluxBody.js, client/src/Component/CreateFlux/CreateFluxBody/CreateFluxBody.module.scss, client/src/Component/CreateFlux/CreateFluxBody/EventSection/Event.module.scss, client/src/Component/CreateFlux/CreateFluxBody/EventSection/EventSection.js, client/src/Component/CreateFlux/CreateFluxHeader/CreateFluxHeader.js, client/src/Component/LandingPage/LandingHeader/LandingHeader.js, client/src/Container/App/App.js, client/src/MaterialUI/Component/Button/Button.js, client/src/MaterialUI/Component/Menu/Menu.js, client/src/MaterialUI/Component/SimpleSelect/SimpleSelect.js, client/src/MaterialUI/Component/TopBar/TopBar.js, client/src/MaterialUI/Import/Import.js, client/src/constants/constants.js, yarn.lock
- Create an event section and action section for creating flux UI
- Add navigation
- Use a mobile-first design approach
- Make create flux page completely mobile responsive 
Fixes #34
=> feat: Complete UI for creating flux and connecting apps

server/src/app.js, server/src/app/models/User.js, server/src/envVariable.js, server/src/thirdparty/README.md, server/src/thirdparty/__tests__/services/github.test.js, server/src/thirdparty/config.js, server/src/thirdparty/githubAPI/config.js, server/src/thirdparty/githubAPI/controller.js, server/src/thirdparty/githubAPI/service.js, server/src/thirdparty/routes/githubRouter.js, server/src/thirdparty/routes/index.js
Integrating Github with Fluxo Application and provide actions and events to be triggered on Application.
Fixes #26 
Will put API Tests once done
=> feat: Github Base API Integration

client/src/Component/CreateFlux/CreateFlux.js, client/src/Component/Dashboard/Dashboard.js, client/src/Component/Dashboard/Dashboard.module.scss, client/src/Component/Dashboard/DeleteFluxModal/DeleteFluxModal.js, client/src/Component/Dashboard/DeleteFluxModal/DeleteFluxModal.module.scss, client/src/Component/Dashboard/dashboardConfig.js, client/src/Component/Header/Header.js, client/src/Container/App/App.js, client/src/MaterialUI/Component/Card/Card.js, client/src/MaterialUI/Component/Card/Card.module.scss, client/src/MaterialUI/Component/Modal/Modal.js, client/src/MaterialUI/Component/SnackBar/SnackBar.js, client/src/MaterialUI/Component/Toggle/Toggle.js, yarn.lock
- User can see all fluxes that are created.
- A user would be able to edit, delete and pause a particular flux
- Complete mobile responsive
Fixes #37
=> feat: Dashboard UI for created fluxes

server/src/app/service/integrationService.js, server/src/thirdparty/githubAPI/config.js, server/src/thirdparty/githubAPI/controller.js, server/src/thirdparty/githubAPI/service.js, server/src/thirdparty/index.js, server/src/thirdparty/routes/githubRouter.js
Integrating Third-Party Actions of Github with Fluxo
Fixes #42 #53
=> feat: Github API Action integration 

client/src/Component/IntegrateButton/IntegrateButton.js, client/src/Component/README.md, client/src/apis/apps/index.js, server/package.json, server/src/app.js, server/src/thirdparty/slackAPI/controller.js, server/views/authStatus.ejs, yarn.lock
- Used polling to find the status
fixes #49
New feature (non-breaking change which adds functionality)
=> feat: Add integrate app button component

server/src/app/controllers/userLogin.js, server/src/app/controllers/userLogout.js, server/src/app/routes/users.js
- Add user detail API
- Add logout API
Fixes #45  #50 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> enhancement: Add user detail and logout api

server/src/app.js, server/src/thirdparty/githubAPI/config.js, server/src/thirdparty/routes/githubRouter.js
- Remove GitHub Router from app.js
- Change route names according to third party API standard.
- Remove /GitHub route specification from getting repo and create an issue.
- Change from array to object structure in GitHub API config.
Fixes #59 #60 #61 
-[x] Github router testing done
=> fix: Github API Routers

Procfile, server/src/app.js
Stop installing yarn again in heroku deployment
Fixes #57 #56
=> fix: Allow PUT,DELETE requests for cors, 

server/src/app/controllers/fluxController.js, server/src/app/models/FluxHistory.js, server/src/app/routes/fluxRouter.js, server/src/app/service/fluxService.js, server/src/app/service/integrationService.js, yarn.lock
- Added models for flux history
- Added API end points
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #64
=> feat: Add flux history

server/src/app/controllers/fluxController.js, server/src/app/models/FluxHistory.js, server/src/app/routes/fluxRouter.js, server/src/app/service/fluxService.js, server/src/app/service/integrationService.js, server/src/thirdparty/__tests__/services/github.test.js, server/src/thirdparty/githubAPI/config.js, yarn.lock
- Fixing of github tests
Fixes #67 
-Jest Unit Testing
=> fix: github routing tests

server/src/app/routes/users.js
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #77 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> fix: Add ensure authentication to auth route

server/src/app/routes/integRouter.js
- Added Integrate Github Router
Fixes #79 
=> fix: Add Github Router to Integrate

.gitignore, server/src/thirdparty/__tests__/services/slack.test.js, server/src/thirdparty/slackAPI/service.js
Resolves:  #85
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Fix: Add same account to multiple users

server/src/app/controllers/userLogin.js, server/src/app/controllers/userRegister.js, server/src/app/service/fluxService.js, server/src/app/service/integrationService.js, server/src/thirdparty/githubAPI/config.js, server/src/thirdparty/githubAPI/controller.js, server/src/thirdparty/githubAPI/service.js, server/src/thirdparty/githubAPI/webhook.js, server/src/thirdparty/routes/githubRouter.js
- Adding events for GitHub in the config file
Fixes # (issue)
=> feat: github api events

server/src/app/__tests__/userRegister.test.js, server/src/app/models/User.js
- Regex updated to new value so the new address can be accommodated.
Fixes #75 
##fix
=> fix: Email in User Schema

server/src/thirdparty/githubAPI/config.js
- New Pull Request Trigger
- Fix: Starred At Trigger
Fixes #91 #92
=> feat: New Trigger Github

client/src/Component/Dashboard/Dashboard.js, client/src/Component/History/History.js, client/src/Component/History/History.module.scss, client/src/Container/App/App.js, client/src/MaterialUI/Component/Card/Card.js, client/src/apis/get-flux/getFlux.js, yarn.lock
Added flux history UI
Fixes #74 
=> feat: Add flux history UI

client/src/Component/Onboarding/Login/Login.js, client/src/Component/Onboarding/SignUp/SignUp.js, client/src/Container/App/App.js, client/src/MaterialUI/Component/Card/Card.js, client/src/MaterialUI/Component/Card/Card.module.scss, client/src/MaterialUI/Component/Menu/Menu.js
Resolves #93
- Change "hava" to "have" on sign-in page
- Change "setting" to "settings" on the menu
- Add abbreviation on dashboard card
Fixes #93
=> bug: Typo Error

client/src/Component/CreateFlux/CreateFluxBody/ActionSection/ActionSection.js, client/src/Component/CreateFlux/CreateFluxBody/EventSection/EventSection.js, client/src/Component/Onboarding/Login/Login.js
- Re-trigger event & action should reload acoounts, events & actions  inputs.
Fixes #95
=> bug: Re-trigger event need to reload event inputs

server/src/thirdparty/githubAPI/controller.js
- Github controller to redirect back to fluxo app
Fixes #98 
=> fix: Changed github controller

server/src/thirdparty/githubAPI/controller.js, server/src/thirdparty/githubAPI/service.js, server/src/thirdparty/routes/githubRouter.js
- Inputs are not loading for github events
Fixes #99 
=> fix: Changes in github route events
